server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
    session:
      timeout: 180m
      cookie:
        max-age: 180m
        name: SSE_JSESSIONID

management:
  endpoints:
    web:
      exposure:
        include: "*"
