server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
    session:
      timeout: 180m
      cookie:
        max-age: 180m
        name: BOARD_JSESSIONID

debug: false
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.board: debug
    org.springframework.web.servlet: debug
    org.hibernate.sql: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace
